sudo: required
services: 
  - docker

before_install: 
  - docker build -t psnehi/angular-docker:latest -f Dockerfile .

script:
  - docker run psnehi/angular-docker:latest npm run test -- --coverage 