sudo: required
services: 
  - docker

before_install: 
  - docker build -t psnehi/angular-docker:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true psnehi/angular-docker:latest npm run test
# - docker run psnehi/angular-docker:latest npm run test -- --coverage