sudo: required
services: 
  - docker

before_install: 
  - docker build -t psnehi/angular-docker:latest -f Dockerfile .

script:
  - docker run -e CI=true psnehi/angular-docker:latest npm run test – --coverages

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-748659118671"
  bucket_path: "frontend"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  