version: '3'
services:
  angular-app:
    image: psnehi/angular-docker:v4
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4200:4200'
    volumes:
      - /app/node_modules
      - .:/app
  